---
  env:
    es6: true
  parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
      jsx: true
  rules:
    semi:
      - error
      - always
    quotes:
      - error
      - single
  extends:
    - "plugin:react/recommended"
