export const types = {
    // Favorites
    FAVORITES_START_FETCHING: 'favorites/START_FETCHING',
    FAVORITES_STOP_FETCHING: 'favorites/STOP_FETCHING',
    FAVORITES_FILL: 'favorites/FAVORITES_FILL',
    FAVORITES_ALBUMS_FILL: 'favorites/ALBUMS_FILL',
    FAVORITES_MEMBERS_FILL: 'favorites/MEMBERS_FILL',
    FAVORITES_PHOTOS_FILL: 'favorites/PHOTOS_FILL',

    // Checker
    CHECKER_SET_CHECK_THING: 'checker/SET_CHECK_THING',
    CHECKER_SET_CHECK_STEP: 'checker/SET_CHECK_STEP',
    CHECKER_SET_CHECK_STATUS: 'checker/SET_CHECK_STATUS',

    // Check groups
    GROUP_MEMBERS_GET: 'admin/GROUP_MEMBERS_GET',

    // Check members
    CHECK_MEMBERS_ALL: 'check_members/ALL',
    CHECK_MEMBERS_WITH_INFO: 'check_members/WITH_INFO',
    CHECK_MEMBERS_CLOSED: 'check_members/CLOSED',
    CHECK_MEMBERS_BANNED: 'check_members/BANNED',
    CHECK_MEMBERS_DELETED: 'check_members/DELETED',
    CHECK_MEMBERS_SELLER: 'check_members/SELLER',

    // Lists settings
    LIST_SETTINGS_SET_ITEMS_LIMIT: 'list_settings/SET_ITEMS_LIMIT',
    LIST_SETTINGS_SET_NUMBER_OF_SKIP: 'list_settings/SET_NUMBER_OF_SKIP',
    LIST_SETTINGS_SET_SORT_TYPE_OF_ITEMS: 'list_settings/SET_SORT_TYPE_OF_ITEMS',
    LIST_SETTINGS_FETCHED_PART_ITEMS: 'list_settings/FETCHED_PART_ITEMS',
    LIST_SETTINGS_SET_TOTAL_ITEMS: 'list_settings/SET_TOTAL_ITEMS',
    LIST_SETTINGS_SET_TOTAL_LOADED_ITEMS: 'list_settings/SET_TOTAL_LOADED_ITEMS',
    LIST_SETTINGS_SET_LOAD_MORE: 'list_settings/SET_LOAD_MORE',
    LIST_SETTINGS_SET_MEMBER_STATUS: 'list_settings/SET_MEMBER_STATUS',
    LIST_SETTINGS_SET_MEMBER_COUNTRY: 'list_settings/SET_MEMBER_COUNTRY',

    // General settings
    LOADING_START: 'general_settings/LOADING_START',
    LOADING_STOP: 'general_settings/LOADING_STOP',
    FETCHING_START: 'general_settings/FETCHING_START',
    FETCHING_STOP: 'general_settings/FETCHING_STOP',
};
